name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install and Build
        run: |
          npm install
          npm run docs:build

      - name: Deploy To github pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: main
          folder: docs/.vuepress/dist
          token: ${{secrets.GITHUB_TOKEN}}
          repository-name: wangchunyus/wangchunyus.github.io
